{
    'name': "Eagle Education Admission",
    'version': '10.0.3.0.0',
    'license': 'LGPL-3',
    'category': 'Education',
    'sequence': 3,
    'summary': "Manage Admissions""",
    'complexity': "easy",
    'author': 'Md. Shaheen Hossain',
    'website': 'http://www.eagle-erp.com',
    'depends': ['openeducat_fees', 'openeducat_core'],
    'data': [
        'views/admission_register_view.xml',
        'views/admission_view.xml',
        'views/admission_sequence.xml',
        'views/student_view.xml',
        'report/report_menu.xml',
        'report/report_admission_analysis.xml',
        'wizard/admission_analysis_wizard_view.xml',
        'admission_menu.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [
        'demo/product_category_demo.xml',
        'demo/product_demo.xml',
        'demo/admission_register_demo.xml',
        'demo/admission_demo.xml',
        'demo/student_fees_details_demo.xml',
    ],
    'test': [
        'test/res_users_creation.yml',
        'test/batch_course_fees.yml',
        'test/admission_register_creation.yml',
    ],
    'images': [
        'static/description/openeducat_admission_banner.jpg',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
